export const buildsStore = [
    {
        status: 'done',
        statusTitle: 'add documentation for postgres scaler',
        branch: 'master',
        author: 'Vadim Makeev',
        id: 'zHuT1Fj',
    },
    {
        status: 'failed',
        statusTitle: 'Super cool UI kit for making websites that look like games',
        branch: 'master',
        author: 'Vlad Rasputin',
        id: 'c3cufbw',
    },
    {
        status: 'processing',
        statusTitle: 'upgrade typescript to 3.8',
        branch: 'master',
        author: 'Uliana Repina',
        id:  '8edr-bj',
    },
    {
        status: 'done',
        statusTitle: 'Merge branch "master" of github.com:jaywcjlove/awesome',
        branch: 'master',
        author: 'Philip Kirkorov',
        id: 'm5UFBEI',
    },
    {
        status: 'done',
        statusTitle: 'replace all `div` to `article`',
        branch: 'master',
        author: 'Vadim Makeev',
        id: 'AjPn-Wa', 
    },
    {
        status: 'processing',
        statusTitle: 'improved accessibility',
        branch: 'master',
        author: 'Uliana Repina',
        id: 'L1Zzxnw',
    },
    {
        status: 'done',
        statusTitle: 'add documentation for postgres scaler',
        branch: 'master',
        author: 'Philip Kirkorov',
        id: 'fVG8aKp',
    },
    {
        status: 'done',
        statusTitle: 'fix: upload 别片类型',
        branch: 'master',
        author: 'Philip Kirkorov',
        id: 'RshmJAi',
    },
    {
        status: 'done',
        statusTitle: 'Form item has default height align with form size',
        branch: 'master',
        author: 'Vadim Makeev',
        id: '6Cs5evI',
    }
]